### ISSUE TITLE
Crash then press "Reset sort" on home page 

### ISSUE THREAD

**Issue by YoukaiDrawing** [dotcreators/moon#1]
![screen](https://github.com/dotcreators/moon/assets/104730018/d3ee42e3-9e46-402e-99c6-0c1b5dabc68e)
![image](https://github.com/dotcreators/moon/assets/104730018/2ad9ce46-d8ea-49a5-9352-706424956fe9)

**Comment by YoukaiDrawing** [comment]
Понял что она вообще нигде не работает, оно и понятно, без любой сортировки не по чему сортировать. Надо её вовсе выпилить.

**Comment by anivire** [comment]
Fixed in https://github.com/dotcreators/moon/commit/8c94f57b4441af69842437a87f9399d73954ef97
